from pathlib import Path
import unittest


class KioskTest(unittest.TestCase):
    def test_server_html_contains_five_button_navigation_hooks(self):
        html = Path("chessboard_app/server.py").read_text(encoding="utf-8")

        self.assertIn("kioskState", html)
        self.assertIn("renderScreen", html)
        self.assertIn("renderWifiList", html)
        self.assertIn("renderWifiPassword", html)
        self.assertIn("PASSWORD_ROWS", html)
        for symbol in ["!", "@", "#", "$", "%", "^", "&", "*", "?"]:
            self.assertIn(f'"{symbol}"', html)
        self.assertIn("activateSelected", html)
        self.assertIn("goBack", html)
        self.assertIn("/auth/lichess/start", html)
        self.assertIn("Connect Lichess", html)
        self.assertIn("renderWifiStatus", html)
        self.assertIn("wifiSignalBars", html)
        self.assertIn("Wi-Fi:", html)
        self.assertIn("Lichess:", html)
        self.assertNotIn("Open OAuth Here", html)
        self.assertIn("Choose Wi-Fi", html)
        self.assertIn("No password needed", html)
        self.assertIn("network.security", html)
        self.assertIn("state.wifi.connected", html)
        self.assertIn('state.wifi.mode === "wired"', html)
        self.assertIn("Board Test", html)
        self.assertIn("LED Test", html)
        self.assertIn("/api/led/test", html)
        self.assertIn("activeControlRoot", html)
        self.assertIn('stage === "wifi"', html)
        self.assertIn("/api/phone-setup-qr.svg", html)
        self.assertNotIn('<img alt="Board setup network QR code"', html)
        self.assertNotIn('<img alt="Board setup page QR code"', html)
        self.assertNotIn('id="mainWifiSsidDisplay" type="text"', html)
        self.assertNotIn("activateRelativeTab", html)
        self.assertNotIn('class="tabButton"', html)
        self.assertNotIn("?.", html)
        self.assertNotIn("=>", html)
        self.assertNotIn("`", html)
        self.assertNotIn("const ", html)
        self.assertNotIn("let ", html)
        self.assertNotIn("async function", html)
        self.assertIn("renderBootError", html)
        self.assertIn("/api/play/friend", html)
        self.assertIn("Play Computer", html)
        self.assertIn("/api/game/submit-physical", html)
        self.assertIn("/api/game/refresh", html)
        self.assertIn("Submit Move", html)
        self.assertIn("Refresh Lichess", html)
        self.assertIn("Lift one piece, place it on the lit destination, then submit.", html)
        self.assertIn("Set up every lit square before starting.", html)
        self.assertIn("That button asked the board to check the physical move.", html)
        self.assertIn("Set the physical board first.", html)
        self.assertIn("Offer/Accept Draw", html)
        self.assertIn("Decline Draw", html)
        self.assertIn("Resign", html)
        self.assertIn("Confirm Resign", html)
        self.assertIn("/api/game/draw/yes", html)
        self.assertIn("/api/game/draw/no", html)
        self.assertIn("/api/game/resign", html)
        self.assertIn("pollLichessGame", html)
        self.assertIn("setInterval(pollLichessGame, 2000)", html)
        self.assertIn("renderPositionBoard(game.pieces", html)
        self.assertIn("function pieceSvg(piece, playerColor)", html)
        self.assertIn("function pieceColorClass(piece, playerColor)", html)
        self.assertIn("gameBoardOrientation(game)", html)
        self.assertIn("Debug:", html)
        self.assertIn("playerColorReason", html)
        self.assertIn("renderDebugRows(game, sync)", html)
        self.assertIn("You are: <code>", html)
        self.assertIn("piece-blue", html)
        self.assertIn("piece-yellow", html)
        self.assertIn("svgPiece", html)
        self.assertIn("function squareCoordinateLabels(square, row, col)", html)
        self.assertIn("grid-template-rows: repeat(8, 1fr)", html)
        self.assertIn("aspect-ratio: 1", html)
        self.assertIn("min-width: 0", html)
        self.assertIn("min-height: 0", html)
        self.assertIn("overflow: hidden", html)
        self.assertIn("coord fileCoord", html)
        self.assertIn("coord rankCoord leftRank", html)
        self.assertIn("coord rankCoord rightRank", html)
        self.assertIn("squareCoordinateLabels(square, row, col)", html)
        self.assertIn("if (row === 7)", html)
        self.assertIn("if (col === 0)", html)
        self.assertIn("if (col === 7)", html)
        self.assertNotIn("bottomRank = black", html)
        self.assertNotIn("boardFrame", html)
        self.assertNotIn("fileLabels", html)
        self.assertNotIn("rankLabels", html)
        self.assertNotIn("translateY(-25px)", html)
        self.assertIn("♞", html)
        self.assertIn("pieceScale(piece)", html)
        self.assertIn("P: {size: 72, y: 71}", html)
        self.assertIn("B: {size: 92, y: 79}", html)
        self.assertIn("return scales[piece] || {size: 82, y: 76}", html)
        self.assertIn("♔", html)
        self.assertIn("♛", html)
        self.assertIn("renderPuzzle", html)
        self.assertIn("New Puzzle", html)
        self.assertIn("Daily Puzzle", html)
        self.assertIn("Start Puzzle", html)
        self.assertIn("Submit Puzzle Move", html)
        self.assertIn("Next Puzzle", html)
        self.assertIn("Refresh Puzzle", html)
        self.assertIn("/api/puzzle/start", html)
        self.assertIn("/api/puzzle/submit-physical", html)
        self.assertIn('fetchPuzzle("/api/puzzles/next")', html)
        self.assertIn("Lights Off", html)
        self.assertIn("Brightness Down", html)
        self.assertIn("/api/live-state", html)
        self.assertIn("refreshLive", html)
        self.assertIn("isLiveScreen", html)
        self.assertIn("setInterval(refreshLive, 60)", html)
        self.assertIn("latestState.leds = state.leds", html)
        self.assertIn(".sq.target::after", html)
        self.assertIn('leds.mode === "legal-targets"', html)
        self.assertIn('leds.mode === "move"', html)
        self.assertIn('targets[square] ? " target" : ""', html)
        self.assertIn("Test Mode", html)

        lichess_screen = html.split("function renderLichessSetup()", 1)[1].split("function renderBoard()", 1)[0]
        self.assertIn("/api/lichess-token-qr.svg", lichess_screen)
        self.assertNotIn("Check Connection", lichess_screen)
        self.assertNotIn("Get API Key", lichess_screen)
        self.assertNotIn("Enter API Key", lichess_screen)
        self.assertNotIn("/api/lichess-manual-token-qr.svg", lichess_screen)
        self.assertNotIn("/api/phone-setup-qr.svg", lichess_screen)

    def test_systemd_services_boot_backend_and_kiosk(self):
        backend = Path("deploy/systemd/chessboard.service").read_text(encoding="utf-8")
        hotspot = Path("deploy/systemd/chessboard-hotspot.service").read_text(encoding="utf-8")
        portal = Path("deploy/systemd/chessboard-portal.service").read_text(encoding="utf-8")
        dpad = Path("deploy/systemd/chessboard-dpad.service").read_text(encoding="utf-8")
        kiosk = Path("deploy/systemd/chessboard-kiosk.service").read_text(encoding="utf-8")

        self.assertIn("run_server.py --hardware", backend)
        self.assertIn(".venv/bin/python3", backend)
        self.assertIn("User=root", backend)
        self.assertIn("--host 0.0.0.0", backend)
        self.assertNotIn("network-online.target", backend)
        self.assertIn("WantedBy=multi-user.target", backend)
        self.assertIn("ensure_wifi_or_hotspot.py", hotspot)
        self.assertIn(".venv/bin/python3", hotspot)
        self.assertIn("Before=chessboard.service", hotspot)
        self.assertIn("setup_portal.py", portal)
        self.assertIn(".venv/bin/python3", portal)
        self.assertIn("dpad_keyboard.py", dpad)
        self.assertIn(".venv/bin/python3", dpad)
        self.assertIn("User=root", dpad)
        self.assertIn("--mode http", dpad)
        self.assertIn("--kiosk", kiosk)
        self.assertIn("--password-store=basic", kiosk)
        self.assertIn("--use-mock-keychain", kiosk)
        self.assertIn("/usr/bin/curl --fail", kiosk)
        self.assertIn("/api/state", kiosk)
        self.assertIn("until /usr/bin/curl", kiosk)
        self.assertIn("--user-data-dir=/home/pi/.config/chessboard-kiosk", kiosk)
        self.assertIn("exec /usr/bin/chromium-browser", kiosk)
        self.assertNotIn("ExecStartPre", kiosk)
        self.assertIn("http://127.0.0.1:8000", kiosk)

    def test_install_script_updates_services(self):
        script = Path("deploy/install_services.sh").read_text(encoding="utf-8")

        self.assertIn(".venv/bin/python3 -m pip", script)
        self.assertIn("pip install -r requirements.txt", script)
        self.assertIn("dnsmasq-shared.d", script)
        self.assertIn("chessboard-portal.service", script)
        self.assertIn("chessboard-dpad.service", script)
        self.assertIn("modprobe uinput", script)
        self.assertIn("systemctl daemon-reload", script)
        self.assertIn("systemctl restart chessboard.service", script)


if __name__ == "__main__":
    unittest.main()
